export const GET_ZONAS = 'GET_ZONAS';
export const ZONAS_ERROR = 'ZONAS_ERROR';
export const LOADING_ZONAS = 'LOADING_ZONAS';

export const GET_CONTADORES = 'GET_CONTADORES';
export const GET_CONTADORES_SECTOR = 'GET_CONTADORES_SECTOR';
export const ADD_CONTADORES = 'ADD_CONTADORES';
export const ADD_CONTADOR_SECTOR = 'ADD_CONTADOR_SECTOR';
export const LOADING_CONTADORES = 'LOADING_CONTADORES';
export const ERROR_CONTADORES = 'ERROR_CONTADORES';
export const UPDATE_CONTADORES = 'UPDATE_CONTADORES';
export const FILTRAR_CONTADORES = 'FILTRAR_CONTADORES';
export const SET_FECHA = 'SET_FECHA';
