// Zonas y Contadores
export const GET_ZONAS = 'GET_ZONAS';
export const GET_CONTADORES = 'GET_CONTADORES';
export const GET_CONTADORES_SECTOR = 'GET_CONTADORES_SECTOR';
export const ADD_CONTADORES = 'ADD_CONTADORES';
export const ADD_CONTADOR_SECTOR = 'ADD_CONTADOR_SECTOR';
export const LOADING_CONTADORES = 'LOADING_CONTADORES';
export const ERROR_CONTADORES = 'ERROR_CONTADORES';
export const UPDATE_CONTADORES = 'UPDATE_CONTADORES';
export const FILTRAR_CONTADORES = 'FILTRAR_CONTADORES';
export const CLEAR_FILTER = 'CLEAR_FILTER';
export const SET_FECHA = 'SET_FECHA';
export const LOADING_ZONAS = 'LOADING_ZONAS';

// Auth
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAIL = 'REGISTER_FAIL';
export const USER_LOADED = 'USER_LOADED';
export const AUTH_ERROR = 'AUTH_ERROR';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const LOGOUT = 'LOGOUT';
export const CLEAR_ERRORS = 'CLEAR_ERRORS';

// Alert
export const SET_ALERT = 'SET_ALERT';
export const REMOVE_ALERT = 'REMOVE_ALERT';
export const LOADING = 'LOADING';
